# TCL File Generated by Component Editor 16.1
# Wed Feb 15 15:40:56 CET 2017
# DO NOT MODIFY


# 
# IIS2ST "IIS2ST" v1.0
#  2017.02.15.15:40:56
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module IIS2ST
# 
set_module_property DESCRIPTION ""
set_module_property NAME IIS2ST
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME IIS2ST
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL iis2st
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file iis2st.vhd VHDL PATH fir/iis2st.vhd TOP_LEVEL_FILE

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL iis2st
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file iis2st.vhd VHDL PATH fir/iis2st.vhd
add_fileset_file iis2st_tb.vhd VHDL PATH fir/iis2st_tb.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clock_bitclk
set_interface_property avalon_streaming_sink associatedReset reset
set_interface_property avalon_streaming_sink dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 0
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink ast_sink_data data Input 24
add_interface_port avalon_streaming_sink ast_sink_ready ready Output 1
add_interface_port avalon_streaming_sink ast_sink_valid valid Input 1
add_interface_port avalon_streaming_sink ast_sink_error error Input 2


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock_bitclk
set_interface_property avalon_streaming_source associatedReset reset
set_interface_property avalon_streaming_source dataBitsPerSymbol 8
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source ast_source_data data Output 24
add_interface_port avalon_streaming_source ast_source_ready ready Input 1
add_interface_port avalon_streaming_source ast_source_valid valid Output 1
add_interface_port avalon_streaming_source ast_source_error error Output 2


# 
# connection point adcdat
# 
add_interface adcdat conduit end
set_interface_property adcdat associatedClock clock
set_interface_property adcdat associatedReset reset
set_interface_property adcdat ENABLED true
set_interface_property adcdat EXPORT_OF ""
set_interface_property adcdat PORT_NAME_MAP ""
set_interface_property adcdat CMSIS_SVD_VARIABLES ""
set_interface_property adcdat SVD_ADDRESS_GROUP ""

add_interface_port adcdat adcdat beginbursttransfer Input 1


# 
# connection point clock_bitclk
# 
add_interface clock_bitclk clock end
set_interface_property clock_bitclk clockRate 0
set_interface_property clock_bitclk ENABLED true
set_interface_property clock_bitclk EXPORT_OF ""
set_interface_property clock_bitclk PORT_NAME_MAP ""
set_interface_property clock_bitclk CMSIS_SVD_VARIABLES ""
set_interface_property clock_bitclk SVD_ADDRESS_GROUP ""

add_interface_port clock_bitclk bitclk clk Input 1


# 
# connection point dacdat
# 
add_interface dacdat conduit end
set_interface_property dacdat associatedClock clock
set_interface_property dacdat associatedReset reset
set_interface_property dacdat ENABLED true
set_interface_property dacdat EXPORT_OF ""
set_interface_property dacdat PORT_NAME_MAP ""
set_interface_property dacdat CMSIS_SVD_VARIABLES ""
set_interface_property dacdat SVD_ADDRESS_GROUP ""

add_interface_port dacdat dacdat writeresponsevalid_n Output 1


# 
# connection point adclrck
# 
add_interface adclrck conduit end
set_interface_property adclrck associatedClock clock
set_interface_property adclrck associatedReset reset
set_interface_property adclrck ENABLED true
set_interface_property adclrck EXPORT_OF ""
set_interface_property adclrck PORT_NAME_MAP ""
set_interface_property adclrck CMSIS_SVD_VARIABLES ""
set_interface_property adclrck SVD_ADDRESS_GROUP ""

add_interface_port adclrck adclrck beginbursttransfer Input 1


# 
# connection point daclrck
# 
add_interface daclrck conduit end
set_interface_property daclrck associatedClock clock
set_interface_property daclrck associatedReset reset
set_interface_property daclrck ENABLED true
set_interface_property daclrck EXPORT_OF ""
set_interface_property daclrck PORT_NAME_MAP ""
set_interface_property daclrck CMSIS_SVD_VARIABLES ""
set_interface_property daclrck SVD_ADDRESS_GROUP ""

add_interface_port daclrck daclrck beginbursttransfer Input 1

